const mongoose = require('mongoose')
const {Schema} = mongoose

const userSchema = new Schema({
    name: String,
    email: {
        type: String,
        unique: true
    },
    password: String,
    visitorId: String,  // ID generated by Fingerprint
    createdAt: { 
        type: Date, 
        default: Date.now 
    },
    suspiciousActivity: {
        type: Boolean,
        default: false
    },
    MFA: {
        type: Boolean,
        default: false
    },
    MFASecret: {
        type: String,
        default: ""
    },
    refreshToken: String
})

const UserModel = mongoose.model('User', userSchema)
module.exports = UserModel